name: Release Extension
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci
        
      - name: Build App
        run: npm run build

      - name: Install Zip utility
        run: apt-get update && apt-get install -y zip

      - name: Zip the output
        run: zip -r grept-${{ github.ref_name }}.zip dist/

      - name: Publish release
        uses: https://code.forgejo.org/forgejo/release-action@v1
        with:
          direction: upload
          release-dir: .
          release-notes: 'See README for installation instructions.'
          token: ${{ secrets.GITHUB_TOKEN }}

